// ATLMFC build numbers (YYMMDD)
#pragma once
 
#define _LIBS_BUILD 31114
#define _LIBS_USER_BUILD "31114"
 
#define _LIBS_PRODUCT_VERSION_MAJOR 14
#define _LIBS_USER_PRODUCT_VERSION_MAJOR "14"
#define _LIBS_PRODUCT_VERSION_MINOR 32
#define _LIBS_USER_PRODUCT_VERSION_MINOR "32"
 
#define _LIBS_FILE_VERSION_MAJOR 14
#define _LIBS_USER_FILE_VERSION_MAJOR "14"
#define _LIBS_FILE_VERSION_MINOR 32
#define _LIBS_USER_FILE_VERSION_MINOR "32"
#define _LIBS_USER_FULL_VER "14.32.31114"
 
#ifndef _LIBS_RBLD
#define _LIBS_RBLD 2
#define _LIBS_USER_RBLD "02"
#endif
